MVC_Learning_ProjectApplication/ViewModels/AddExamViewModel.cs
using MVC_Learning_ProjectApplication.Models;

namespace MVC_Learning_ProjectApplication.ViewModels
{
    public class AddExamViewModel
    {
        public int SelectedClassId { get; set; }
        public IEnumerable<Class> Classes {  get; set; } = new List<Class>(); 
        public int SelectedStudentId { get; set; }
        public int? CourseWork {  get; set; }
        public int? Midterm {  get; set; }
        public int? FinalWork {  get; set; }
    }
}

MVC_Learning_ProjectApplication/Controllers/AddExamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Learning_ProjectApplication.Models;
using MVC_Learning_ProjectApplication.ViewModels;

namespace MVC_Learning_ProjectApplication.Controllers
{
    public class AddExamController : Controller
    {
        private readonly AppDbContext _context;

        public AddExamController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var addExamViewModel = new AddExamViewModel
            {
                Classes = _context.Classes.ToList()
            };

            return View(addExamViewModel);
        }

        public IActionResult AddExamStudentPartial(int studentId)
        {
            var student = _context.Students
                .Include(s => s.ClassC)
                .FirstOrDefault(s => s.Id == studentId);

            var results = _context.Exams
                .Where(x => x.DeanName == "Dean" && x.StudentId == studentId)
                .OrderByDescending(x => x.DateOfModificition)
                .FirstOrDefault();

            var model = new AddExamViewModel
            {
                SelectedStudentId = studentId,
                CourseWork = results?.CourseWork ?? 0,
                Midterm = results?.Midterm ?? 0,
                FinalWork = results?.Final_work ?? 0
            };

            ViewBag.Student = student;
            return PartialView("_IntroStudent", model);
        }

        [HttpPost]
        public IActionResult AddExam(AddExamViewModel addExamViewModel)
        {
            if (ModelState.IsValid)
            {
                var student = _context.Students.Find(addExamViewModel.SelectedStudentId);
                var classC = _context.Classes.Find(addExamViewModel.SelectedClassId);

                if (student != null && classC != null)
                {
                    var exam = new Exam
                    {
                        DeanName = "Dean",
                        StudentId = student.Id,
                        ClassId = classC.Id,
                        CourseWork = addExamViewModel.CourseWork ?? 0,
                        Midterm = addExamViewModel.Midterm ?? 0,
                        Final_work = addExamViewModel.FinalWork ?? 0,
                        DateOfModificition = DateTime.Now
                    };

                    _context.Exams.Add(exam);
                    _context.SaveChanges();
                }
            }

            addExamViewModel.Classes = _context.Classes.ToList();

            var refreshedStudent = _context.Students.Find(addExamViewModel.SelectedStudentId);
            addExamViewModel.SelectedClassId = refreshedStudent?.ClassId ?? 0;

            return View("Index", addExamViewModel);
        }
    }
}

MVC_Learning_ProjectApplication/ViewComponents/ExamsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

public class ExamsViewComponent : ViewComponent
{
    private readonly ExamsRepository _repo;

    public ExamsViewComponent(ExamsRepository repo)
    {
        _repo = repo;
    }

    public IViewComponentResult Invoke(string deanName)
    {
        var exams = _repo.GetByDayAndDean(deanName, DateTime.Now);
        return View(exams);
    }
}

MVC_Learning_ProjectApplication/Views/AddExam/Index.cshtml
@model AddExamViewModel
@section title{
	<div class="row">
		<div class="col-7"><h3>Dean's Console</h3></div>
		<div class="col-3">
		</div>
	</div>
}
<br />
<div class="row">
	<div class="col-4">
		<div class="text-danger" asp-validation-Summary="All"></div>
		<div class="row mb-3">
			<select asp-for="SelectedClassId" class="form-control">
				<option value="">-- Select Class --</option>
				@if (Model.Classes != null && Model.Classes.Count() > 0)
				{
					@foreach (var classC in Model.Classes)
					{
						<option value="@classC.Id">@classC.Name</option>
					}
				}
			</select>
		</div>
		<br />
		<div id="studentsPartial">
			@*Students List*@
		</div>
		<br />
		@*Exam results Form*@
		<form method="post" asp-controller="AddExam" asp-action="AddExam" id="formSale">
			<input type="hidden" id="SelectedClassIdHidden" name="SelectedClassId" />
			<input asp-for="SelectedStudentId" type="hidden" />
			<input type="hidden" id="SelectedClassIdHidden" name="SelectedClassId" />

			<div id="studentDetailPartial">
				@* Textboxex will be here*@
			</div>
			<br />
			<div class="row mb-3">
				<div class="col-2">
					<input type="submit" class="btn btn-primary" value="Submit" />
				</div>
			</div>
		</form>

	</div>
	<div class="col">
		@await Component.InvokeAsync("Exams", "Dean")
	</div>
</div>
@section Scripts {
	<script>
		$(function () {
			selectedClassIdGlobal = $("#SelectedClassId").val();

			$("#formSale").hide();

			var selectedClassId = $("#SelectedClassId").val();
			if(selectedClassId>0){
				loadStudents(selectedClassId);
			}

			$("#SelectedClassId").on("change", function () {
				selectedClassIdGlobal = $(this).val();
				$("#SelectedClassIdHidden").val(selectedClassIdGlobal);
				loadStudents(selectedClassIdGlobal);
			});


			$('#studentsPartial').on('click', '.student-row', function () {
				$('.student-row').removeClass('highlight');
				$(this).addClass('highlight');

				var studId = $(this).attr('student-id');

				$('#studentDetailPartial').load('/AddExam/AddExamStudentPartial', { studentId: studId  });

				if(studId>0){
					$("#SelectedStudentId").val(studId);
					$("#SelectedClassIdHidden").val(selectedClassIdGlobal);
					$("#formSale").show();
				}
				else{
					$("#formSale").hide();
				}
			});
		});
		function loadStudents(classId){
			$("#studentsPartial").load("/Students/StudentsByClassPartial", { classId: classId });
			$("#studentDetailPartial").html("");
			$("#formSale").hide();
		}
	</script>
}

MVC_Learning_ProjectApplication/Views/AddExam/_IntroStudent.cshtml
@model AddExamViewModel
@{
    var student = ViewBag.Student as Student;
}

@if (student != null)
{
    <div class="border p-2 mb-2">
        <strong>Student Name:</strong> @student.Name<br />
        <strong>Student Surname:</strong> @student.SurName<br />
    </div>
}
else
{
    <div class="alert alert-warning">Student not found.</div>
}


<div class="form-group">
    <label asp-for="CourseWork">Course Work Result</label>
    <input asp-for="CourseWork" class="form-control" type="number" min="0" max="100" />
    <span asp-validation-for="CourseWork" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Midterm">Midterm Result</label>
    <input asp-for="Midterm" class="form-control" type="number" min="0" max="100" />
    <span asp-validation-for="Midterm" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="FinalWork">Final Exam Result</label>
    <input asp-for="FinalWork" class="form-control" type="number" min="0" max="100" />
    <span asp-validation-for="FinalWork" class="text-danger"></span>
</div>